CREATE TABLE topicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(500) NOT NULL,
    mensaje TEXT NOT NULL,
    fechaDeCreacionTopico TIMESTAMP,
    fechaUltimaEdicionTopico TIMESTAMP,
    statusTopico VARCHAR(50) NOT NULL,
    autorTopico BIGINT NOT NULL,
    curso BIGINT NOT NULL,
    CONSTRAINT fk_autorTopico FOREIGN KEY (autorTopico) REFERENCES usuarios(id),
    CONSTRAINT fk_curso FOREIGN KEY (curso) REFERENCES cursos(id)
);
